version: '3.8'

services:
  # 📰 The News API
  news-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: the-news-api
    ports:
      - "3000:3000"
    volumes:
      # Hot reload: código fuente sincronizado (sin :ro para editar en code-server)
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../tsconfig.json:/app/tsconfig.json
      # Volume nombrado para node_modules (performance)
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      # ✅ URI corregida con las credenciales correctas
      - MONGODB_URI=mongodb://admin:admin123@mongo:27017/thenews?authSource=admin
      - API_NAME=The News API
      - API_VERSION=1.0.0
      - DEBUG=the-news:*
      - LOG_LEVEL=debug
    depends_on:
      - mongo
    networks:
      - news-network
    restart: unless-stopped

  # 🗄️ MongoDB Database
  mongo:
    image: mongo:7-jammy
    container_name: the-news-mongo
    ports:
      - "27017:27017"
    volumes:
      - news_mongo_data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    environment:
      # ✅ Usuario administrador (solo para setup inicial)
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      # ✅ Base de datos de la aplicación
      - MONGO_INITDB_DATABASE=thenews
    networks:
      - news-network
    restart: unless-stopped

  # 🖥️ MongoDB Admin UI (opcional para principiantes)
  mongo-express:
    image: mongo-express:1-20
    container_name: the-news-mongo-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - news-network
    restart: unless-stopped

# 💾 Volúmenes persistentes
volumes:
  news_mongo_data:
    driver: local
  node_modules:
    driver: local

# 🌐 Red interna
networks:
  news-network:
    driver: bridge