version: '3.8'

services:
  # 📰 The News API
  news-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: the-news-api
    ports:
      - "3000:3000"
    volumes:
      # Hot reload: código fuente sincronizado
      - ../src:/app/src:ro
      - ../package.json:/app/package.json:ro
      - ../tsconfig.json:/app/tsconfig.json:ro
      # Volume nombrado para node_modules (performance)
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/thenews
      - API_NAME=The News API
      - API_VERSION=1.0.0
      - DEBUG=the-news:*
      - LOG_LEVEL=debug
    depends_on:
      - mongo
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🗄️ MongoDB Database
  mongo:
    image: mongo:7-jammy
    container_name: the-news-mongo
    ports:
      - "27017:27017"
    volumes:
  # Sin :ro para permitir escritura
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../tsconfig.json:/app/tsconfig.json
      - node_modules:/app/node_modules
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=news123
      - MONGO_INITDB_DATABASE=thenews
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.admin().ping()"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 🖥️ MongoDB Admin UI
  mongo-express:
    image: mongo-express:1-20
    container_name: the-news-mongo-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=news123
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_SITE_BASEURL=/
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - news-network
    restart: unless-stopped

# 💾 Volúmenes persistentes
volumes:
  news_mongo_data:
    driver: local
  node_modules:
    driver: local

# 🌐 Red interna
networks:
  news-network:
    driver: bridge
    name: the-news-network